DATES
  01 'SEP' 1957 /
/

WTRACER
-- name tracer concentr factor group
 '29SHKA' 'W29' 1 1* '*' /
 '75' 'W75' 1 1* '*' /
 '67' 'W67' 1 1* '*' /
/
 DATES
  01 'OCT' 1957 /
/
WTRACER
-- name tracer concentr factor group
 '69' 'W69' 1 1* '*' /
  /
DATES
  01 'MAY' 1958 /
/

WTRACER
-- name tracer concentr factor group
 '70' 'W70' 1 1* '*' /
/
 DATES
  01 'JUN' 1958 /
/

 DATES
  07 'JUL' 1961 /
/
WTRACER
-- name tracer concentr factor group
 '76' 'W76' 1 1* '*' /
/

 DATES
  01 'AUG' 1961 /
/
